### ISSUE TITLE
Name suggestion: rename dateOrDateTimeToIso8601String to toIso8601

### ISSUE THREAD

**Issue by MartinSStewart** [dillonkearns/elm-date-or-date-time#1]
https://package.elm-lang.org/packages/dillonkearns/elm-date-or-date-time/1.0.0/DateOrDateTime#dateOrDateTimeToIso8601String is a pretty long function name and parts of it seem unnecessary. Since it's in a module called DateOrDateTime, the leading `dateOrDateTime` isn't needed (at least, I'd expect people to write the function qualified). And the `String` part at the end doesn't seem needed since you can look at the type signature.

**Comment by dillonkearns** [comment]
Great point! `DateOrDateTime.toIso8601` seems much better 👍

**Comment by dillonkearns** [comment]
Fixed in 2.0.0!

https://github.com/dillonkearns/elm-date-or-date-time/commit/810a3b44d691d18cc830418a7e49b0d959f81a4d
